services:
  server:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgresql://admin:admin123@server-db:5432/fl_server
    depends_on:
      - server-db
    networks:
      - flnet

  client1:
    build: ./client1
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgresql://client:client123@client1-db:5432/fl_client
    depends_on:
      - client1-db
    networks:
      - flnet

  client2:
    build: ./client2
    ports:
      - "8083:8083"
    environment:
      DATABASE_URL: postgresql://client:client123@client2-db:5432/fl_client
    depends_on:
      - client2-db
    networks:
      - flnet

  server-db:
    image: postgres:15
    environment:
      POSTGRES_USER=admin
      POSTGRES_PASSWORD=admin123
      POSTGRES_DB=fl_server
    ports:
      - "5432:5432"
    volumes:
      - server_data:/var/lib/postgresql/data
    networks:
      - flnet
    
  client1-db:
    image: postgres:15
    environment:
      POSTGRES_USER=client
      POSTGRES_PASSWORD=client123
      POSTGRES_DB=fl_client
    volumes:
      - client1_data:/var/lib/postgresql/data
    networks:
      - flnet
    
  client2-db:
    image: postgres:15
    environment:
      POSTGRES_USER=client
      POSTGRES_PASSWORD=client123
      POSTGRES_DB=fl_client
    volumes:
      - client2_data:/var/lib/postgresql/data
    networks:
      - flnet

networks:
  flnet:
    driver: bridge

volumes:
  server_data:
  client1_data:
  client2_data:
